// Function to generate slugs from titles
const slugify = (text) => text.toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g, '');

export const projectsData = [
  {
    title: 'Reno App',
    slug: 'reno-app',
    description: 'A mobile-first crypto exchange application with instant swap functionality.',
    category: 'Fintech',
    projectType: 'Crypto Exchange App',
    overview: 'Built for fast and seamless crypto swaps with a smooth mobile UX.',
    impact: ['Enabled instant crypto swaps', 'Optimized mobile trading experience'],
    techStack: ['React Native'],
    images: [
      'https://picsum.photos/seed/reno-crypto-1/800/600',
      'https://picsum.photos/seed/reno-crypto-2/800/600',
      'https://picsum.photos/seed/reno-crypto-3/800/600',
      'https://picsum.photos/seed/reno-crypto-4/800/600',
      'https://picsum.photos/seed/reno-crypto-5/800/600',
      'https://picsum.photos/seed/reno-crypto-6/800/600',
    ],
    isFeatured: true,
  },
  {
    title: 'NexusChat',
    slug: 'nexuschat',
    description: 'Real-time communication platform supporting chat, group chat, and calls.',
    category: 'Communication',
    projectType: 'Chat & Calling Platform',
    overview: 'Socket-powered system enabling low-latency messaging and voice calls.',
    impact: ['Real-time messaging at scale', 'Improved team and community communication'],
    techStack: ['Next.js', 'Node.js', 'Socket.IO'],
    images: [
      'https://picsum.photos/seed/nexuschat-1/800/600',
      'https://picsum.photos/seed/nexuschat-2/800/600',
      'https://picsum.photos/seed/nexuschat-3/800/600',
      'https://picsum.photos/seed/nexuschat-4/800/600',
      'https://picsum.photos/seed/nexuschat-5/800/600',
      'https://picsum.photos/seed/nexuschat-6/800/600',
    ],
    isFeatured: true,
  },
  {
    title: 'Insight Bot Trader',
    slug: 'insight-bot-trader',
    description: 'Automated P2P crypto trading bot for ad placement and payment fulfillment.',
    category: 'Fintech',
    projectType: 'P2P Trading Automation',
    overview: 'Automates P2P trading flow from ad placement to payment confirmation.',
    impact: ['Reduced manual P2P trading effort', 'Improved trade execution speed'],
    techStack: ['Node.js'],
    images: [
      'https://picsum.photos/seed/insight-bot-1/800/600',
      'https://picsum.photos/seed/insight-bot-2/800/600',
      'https://picsum.photos/seed/insight-bot-3/800/600',
      'https://picsum.photos/seed/insight-bot-4/800/600',
      'https://picsum.photos/seed/insight-bot-5/800/600',
    ],
    isFeatured: true,
  },
  {
    title: 'Bloomty',
    slug: 'bloomty',
    description: 'A multi-platform service marketplace and business management solution.',
    category: 'Business',
    projectType: 'Marketplace Platform',
    overview: 'Web and mobile solution supporting service listings, bookings, and payments.',
    impact: ['Centralized service management', 'Improved customer booking flow'],
    techStack: ['Next.js', 'Node.js', 'React Native'],
    images: [
      'https://picsum.photos/seed/bloomty-marketplace-1/800/600',
      'https://picsum.photos/seed/bloomty-marketplace-2/800/600',
      'https://picsum.photos/seed/bloomty-marketplace-3/800/600',
      'https://picsum.photos/seed/bloomty-marketplace-4/800/600',
      'https://picsum.photos/seed/bloomty-marketplace-5/800/600',
      'https://picsum.photos/seed/bloomty-marketplace-6/800/600',
    ],
    isFeatured: false,
  },
  {
    title: 'Hotel Management System',
    slug: 'hotel-management-system',
    description: 'A property management system tailored for hotels and short-stay businesses.',
    category: 'Hospitality',
    projectType: 'Hotel Property Management System',
    overview: 'Manages reservations, rooms, billing, and operational reporting.',
    impact: ['Streamlined hotel operations', 'Reduced manual booking errors'],
    techStack: ['Next.js', 'Node.js'],
    images: [
      'https://picsum.photos/seed/omnia-pms-1/800/600',
      'https://picsum.photos/seed/omnia-pms-2/800/600',
      'https://picsum.photos/seed/omnia-pms-3/800/600',
      'https://picsum.photos/seed/omnia-pms-4/800/600',
      'https://picsum.photos/seed/omnia-pms-5/800/600',
      'https://picsum.photos/seed/omnia-pms-6/800/600',
    ],
    isFeatured: true,
  },
  {
    title: 'Klimars Space Gym Management System',
    slug: 'klimars-space-gym',
    description: 'QR-enabled gym management system for access control and member tracking.',
    category: 'Fitness',
    projectType: 'Gym Management System',
    overview: 'Handles memberships, attendance, and mobile access using QR codes.',
    impact: ['Improved member check-in efficiency', 'Automated attendance tracking'],
    techStack: ['Next.js', 'Node.js', 'React Native'],
    images: [
      'https://picsum.photos/seed/klimars-gym-1/800/600',
      'https://picsum.photos/seed/klimars-gym-2/800/600',
      'https://picsum.photos/seed/klimars-gym-3/800/600',
      'https://picsum.photos/seed/klimars-gym-4/800/600',
      'https://picsum.photos/seed/klimars-gym-5/800/600',
      'https://picsum.photos/seed/klimars-gym-6/800/600',
    ],
    isFeatured: true,
  },
  {
    title: 'Lampsiheirs',
    slug: 'lampsiheirs',
    description: 'Corporate and brand-focused website with a modern UI.',
    category: 'Corporate',
    projectType: 'Business Website',
    overview: 'Clean and professional web presence for brand communication.',
    impact: ['Enhanced online brand credibility'],
    techStack: ['Next.js'],
    images: [
      'https://picsum.photos/seed/lampsiheirs-1/800/600',
      'https://picsum.photos/seed/lampsiheirs-2/800/600',
      'https://picsum.photos/seed/lampsiheirs-3/800/600',
      'https://picsum.photos/seed/lampsiheirs-4/800/600',
      'https://picsum.photos/seed/lampsiheirs-5/800/600',
    ],
    isFeatured: false,
  },
  {
    title: 'Efemena Construction',
    slug: 'efemena-construction',
    description: 'Company website showcasing construction projects and services.',
    category: 'Corporate',
    projectType: 'Construction Company Website',
    overview: 'Designed to present projects, services, and company profile clearly.',
    impact: ['Improved client trust and inquiries'],
    techStack: ['Next.js'],
    images: [
      'https://picsum.photos/seed/efemena-construction-1/800/600',
      'https://picsum.photos/seed/efemena-construction-2/800/600',
      'https://picsum.photos/seed/efemena-construction-3/800/600',
      'https://picsum.photos/seed/efemena-construction-4/800/600',
      'https://picsum.photos/seed/efemena-construction-5/800/600',
    ],
    isFeatured: false,
  },
  {
    title: 'Creative Emmy',
    slug: 'creative-emmy',
    description: 'Portfolio website for a creative brand and digital services.',
    category: 'Creative',
    projectType: 'Portfolio Website',
    overview: 'Showcases creative works with a visually engaging layout.',
    impact: ['Stronger personal brand presence'],
    techStack: ['Next.js'],
    images: [
      'https://picsum.photos/seed/creative-emmy-1/800/600',
      'https://picsum.photos/seed/creative-emmy-2/800/600',
      'https://picsum.photos/seed/creative-emmy-3/800/600',
      'https://picsum.photos/seed/creative-emmy-4/800/600',
      'https://picsum.photos/seed/creative-emmy-5/800/600',
    ],
    isFeatured: false,
  },
  {
    title: 'Learning Management System',
    slug: 'learning-management-system',
    description: 'Comprehensive system for managing school operations and learning flow.',
    category: 'EdTech',
    projectType: 'Learning Management System',
    overview: 'Supports student management, classes, assessments, and progress tracking.',
    impact: ['Digitized academic workflows', 'Improved student performance tracking'],
    techStack: ['Next.js', 'Node.js'],
    images: [
      'https://picsum.photos/seed/school-ems-1/800/600',
      'https://picsum.photos/seed/school-ems-2/800/600',
      'https://picsum.photos/seed/school-ems-3/800/600',
      'https://picsum.photos/seed/school-ems-4/800/600',
      'https://picsum.photos/seed/school-ems-5/800/600',
      'https://picsum.photos/seed/school-ems-6/800/600',
    ],
    isFeatured: true,
  },
  {
    title: 'Doi Creative',
    slug: 'doi-creative',
    description: 'Creative agency website highlighting services and past works.',
    category: 'Creative',
    projectType: 'Agency Website',
    overview: 'Modern agency site focused on conversions and visual storytelling.',
    impact: ['Increased client engagement'],
    techStack: ['Next.js'],
    images: [
      'https://picsum.photos/seed/doi-creative-1/800/600',
      'https://picsum.photos/seed/doi-creative-2/800/600',
      'https://picsum.photos/seed/doi-creative-3/800/600',
      'https://picsum.photos/seed/doi-creative-4/800/600',
      'https://picsum.photos/seed/doi-creative-5/800/600',
    ],
    isFeatured: false,
  },
];

export const getProjects = () => projectsData;
export const getFeaturedProjects = () => projectsData.filter(p => p.isFeatured).slice(0, 4);
export const getProjectBySlug = (slug) => projectsData.find(p => p.slug === slug);