// Function to generate slugs from titles
const slugify = (text) => text.toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g, '');

export const projectsData = [
  {
    title: 'Reno App',
    slug: 'reno-app',
    description: 'A mobile-first crypto exchange application with instant swap functionality.',
    category: 'Fintech',
    projectType: 'Crypto Exchange App',
    overview: 'Built for fast and seamless crypto swaps with a smooth mobile UX.',
    impact: ['Enabled instant crypto swaps', 'Optimized mobile trading experience'],
    techStack: ['React Native'],
    images: [
      '/reno/original-5ae26a232c2de792dde565fe8903b319.png',
      '/reno/logo22.png',
      '/reno/Screenshot_20251217_021859_Reno.jpg',
      '/reno/Screenshot_20251217_021909_Reno.jpg',
      '/reno/Screenshot_20251217_021920_Reno.jpg',
      '/reno/Screenshot_20251217_021929_Reno.jpg',
      '/reno/Screenshot_20251217_021935_Reno.jpg',
      '/reno/Screenshot_20251217_021945_Reno.jpg',
      '/reno/Screenshot_20251217_022005_Reno.jpg',
    ],
    isFeatured: true,
  },
  {
    title: 'NexusChat',
    slug: 'nexuschat',
    description: 'Real-time communication platform supporting chat, group chat, and calls.',
    category: 'Communication',
    projectType: 'Chat & Calling Platform',
    overview: 'Socket-powered system enabling low-latency messaging and voice calls.',
    impact: ['Real-time messaging at scale', 'Improved team and community communication'],
    techStack: ['Next.js', 'Node.js', 'Socket.IO'],
    images: [
      '/nexus-chat/Free Laptop & Smart Phone Mockup For Your Design Presentation2.png',
      '/nexus-chat/localhost_3000_.png',
      '/nexus-chat/localhost_3000_signin (1).png',
      '/nexus-chat/localhost_3000_signin (2).png',
      '/nexus-chat/localhost_3000_signin.png',
      '/nexus-chat/Screenshot 2025-09-25 033852.png',
      '/nexus-chat/WhatsApp Image 2025-12-18 at 09.35.31_3c1fe245.jpg',
      '/nexus-chat/WhatsApp Image 2025-12-18 at 09.35.32_1561e45f.jpg',
      '/nexus-chat/WhatsApp Image 2025-12-18 at 09.35.32_3e778a7c.jpg',
    ],
    isFeatured: true,
  },
  {
    title: 'Insight Bot Trader',
    slug: 'insight-bot-trader',
    description: 'Automated P2P crypto trading bot for ad placement and payment fulfillment.',
    category: 'Fintech',
    projectType: 'P2P Trading Automation',
    overview: 'Automates P2P trading flow from ad placement to payment confirmation.',
    impact: ['Reduced manual P2P trading effort', 'Improved trade execution speed'],
    techStack: ['Node.js'],
    images: [
      '/insight bot/Blog - Baytech Consulting.jpeg',
      '/insight bot/Screenshot_20251218_112832_Bybit.jpg',
      '/insight bot/Screenshot_20251218_112920_Bybit.jpg',
    ],
    isFeatured: false,
  },
  {
    title: 'Bloomty',
    slug: 'bloomty',
    description: 'A multi-platform service marketplace and business management solution.',
    category: 'Business',
    projectType: 'Marketplace Platform',
    overview: 'Web and mobile solution supporting service listings, bookings, and payments.',
    impact: ['Centralized service management', 'Improved customer booking flow'],
    techStack: ['Next.js', 'Node.js', 'React Native'],
    images: [
      '/bloomty/beauty-mockup.png',
      '/bloomty/Bloom-Ty - Google Chrome 18-Dec-25 11_32_09 AM.png',
      '/bloomty/Bloom-Ty - Google Chrome 18-Dec-25 11_32_09 AM.png',
      '/bloomty/bloom-ty.vercel.app_ (1).png',
      '/bloomty/bloom-ty.vercel.app_.png',
      '/bloomty/222.png',
      '/bloomty/221.png',
      '/bloomty/Screenshot_20251218_113457_Chrome.jpg',
      '/bloomty/Screenshot_20251218_113515_Chrome.jpg',
      '/bloomty/Screenshot_20251218_113522_Chrome.jpg',
      '/bloomty/Screenshot_20251218_113616_Chrome.jpg',
      '/bloomty/Screenshot_20251218_113622_Chrome.jpg',
    ],
    isFeatured: true,
  },
  // {
  //   title: 'Hotel Management System',
  //   slug: 'hotel-management-system',
  //   description: 'A property management system tailored for hotels and short-stay businesses.',
  //   category: 'Hospitality',
  //   projectType: 'Hotel Property Management System',
  //   overview: 'Manages reservations, rooms, billing, and operational reporting.',
  //   impact: ['Streamlined hotel operations', 'Reduced manual booking errors'],
  //   techStack: ['Next.js', 'Node.js'],
  //   images: [
  //     'https://picsum.photos/seed/omnia-pms-1/800/600',
  //     'https://picsum.photos/seed/omnia-pms-2/800/600',
  //     'https://picsum.photos/seed/omnia-pms-3/800/600',
  //     'https://picsum.photos/seed/omnia-pms-4/800/600',
  //     'https://picsum.photos/seed/omnia-pms-5/800/600',
  //     'https://picsum.photos/seed/omnia-pms-6/800/600',
  //   ],
  //   isFeatured: false,
  // },
  // {
  //   title: 'Klimars Space Gym',
  //   slug: 'klimars-space-gym',
  //   description: 'QR-enabled gym management system for access control and member tracking.',
  //   category: 'Fitness',
  //   projectType: 'Gym Management System',
  //   overview: 'Handles memberships, attendance, and mobile access using QR codes.',
  //   impact: ['Improved member check-in efficiency', 'Automated attendance tracking'],
  //   techStack: ['Next.js', 'Node.js', 'React Native'],
  //   images: [
  //     'https://picsum.photos/seed/klimars-gym-1/800/600',
  //     'https://picsum.photos/seed/klimars-gym-2/800/600',
  //     'https://picsum.photos/seed/klimars-gym-3/800/600',
  //     'https://picsum.photos/seed/klimars-gym-4/800/600',
  //     'https://picsum.photos/seed/klimars-gym-5/800/600',
  //     'https://picsum.photos/seed/klimars-gym-6/800/600',
  //   ],
  //   isFeatured: false,
  // },
  {
    title: 'Lampsiheirs',
    slug: 'lampsiheirs',
    description: 'Corporate and brand-focused website with a modern UI.',
    category: 'Corporate',
    projectType: 'Business Website',
    overview: 'Clean and professional web presence for brand communication.',
    impact: ['Enhanced online brand credibility'],
    techStack: ['Next.js'],
    images: [
      '/lampsi heirs/Bloom-Ty - Google Chrome 18-Dec-25 12_00_10 PM.png',
      '/lampsi heirs/Bloom-Ty - Google Chrome 18-Dec-25 12_00_23 PM.png',
      '/lampsi heirs/Bloom-Ty - Google Chrome 18-Dec-25 12_00_38 PM.png',
      '/lampsi heirs/Bloom-Ty - Google Chrome 18-Dec-25 12_00_52 PM.png',
      '/lampsi heirs/Bloom-Ty - Google Chrome 18-Dec-25 12_01_09 PM.png',
      '/lampsi heirs/Screenshot_20251218_114714_Chrome.jpg',
      '/lampsi heirs/Screenshot_20251218_114744_Chrome.jpg',
      '/lampsi heirs/Screenshot_20251218_114804_Chrome.jpg',
      '/lampsi heirs/Screenshot_20251218_114815_Chrome.jpg',
      '/lampsi heirs/www.lampsiheirs.com_ (1).png',
      '/lampsi heirs/www.lampsiheirs.com_.png',
    ],
    isFeatured: false,
  },
  {
    title: 'Efemena Construction',
    slug: 'efemena-construction',
    description: 'Company website showcasing construction projects and services.',
    category: 'Corporate',
    projectType: 'Construction Company Website',
    overview: 'Designed to present projects, services, and company profile clearly.',
    impact: ['Improved client trust and inquiries'],
    techStack: ['Next.js'],
    images: [
      '/efemena construction/Bloom-Ty - Google Chrome 18-Dec-25 11_58_13 AM.png',
      '/efemena construction/Bloom-Ty - Google Chrome 18-Dec-25 11_58_27 AM.png',
      '/efemena construction/Bloom-Ty - Google Chrome 18-Dec-25 11_58_35 AM.png',
      '/efemena construction/efemena-construction.vercel.app_ (1).png',
      '/efemena construction/efemena-construction.vercel.app_.png',
      '/efemena construction/Screenshot_20251218_114606_Chrome.jpg',
      '/efemena construction/Screenshot_20251218_114614_Chrome.jpg',
      '/efemena construction/Screenshot_20251218_114622_Chrome.jpg',
      '/efemena construction/Screenshot_20251218_114631_Chrome.jpg',
      '/efemena construction/Screenshot_20251218_114637_Chrome.jpg',
      '/efemena construction/Screenshot_20251218_114657_Chrome.jpg',
    ],
    isFeatured: false,
  },
  {
    title: 'Creative Emmy',
    slug: 'creative-emmy',
    description: 'Portfolio website for a creative brand and digital services.',
    category: 'Creative',
    projectType: 'Portfolio Website',
    overview: 'Showcases creative works with a visually engaging layout.',
    impact: ['Stronger personal brand presence'],
    techStack: ['Next.js'],
    images: [
      '/creative emmy/Bloom-Ty - Google Chrome 18-Dec-25 11_57_37 AM.png',
      '/creative emmy/Bloom-Ty - Google Chrome 18-Dec-25 11_57_23 AM.png',
      '/creative emmy/Bloom-Ty - Google Chrome 18-Dec-25 11_57_44 AM.png',
      '/creative emmy/Bloom-Ty - Google Chrome 18-Dec-25 11_57_57 AM.png',
      '/creative emmy/creatie-emmy.vercel.app_.png',
      '/creative emmy/Screenshot_20251218_114327_Chrome.jpg',
      '/creative emmy/Screenshot_20251218_114333_Chrome.jpg',
      '/creative emmy/Screenshot_20251218_114402_Chrome.jpg',
      '/creative emmy/Screenshot_20251218_114410_Chrome.jpg',
      '/creative emmy/Screenshot_20251218_114419_Chrome.jpg',
      '/creative emmy/Screenshot_20251218_114430_Chrome.jpg',
    ],
    isFeatured: false,
  },
  {
    title: 'Learning Management System',
    slug: 'learning-management-system',
    description: 'Comprehensive system for managing school operations and learning flow.',
    category: 'EdTech',
    projectType: 'Learning Management System',
    overview: 'Supports student management, classes, assessments, and progress tracking.',
    impact: ['Digitized academic workflows', 'Improved student performance tracking'],
    techStack: ['Next.js', 'Node.js'],
    images: [
      '/lms/online-school-olive.vercel.app_ (12).png',
      '/lms/online-school-olive.vercel.app_ (10).png',
      '/lms/online-school-olive.vercel.app_ (11).png',
      '/lms/online-school-olive.vercel.app_ (13).png',
      '/lms/Screenshot_20251218_114906_Chrome.jpg',
      '/lms/Screenshot_20251218_114954_Chrome.jpg',
      '/lms/Screenshot_20251218_115012_Chrome.jpg',
      '/lms/Screenshot_20251218_115023_Chrome.jpg',
    ],
    isFeatured: true,
  },
  {
    title: 'Doi Creative',
    slug: 'doi-creative',
    description: 'Creative agency website highlighting services and past works.',
    category: 'Creative',
    projectType: 'Agency Website',
    overview: 'Modern agency site focused on conversions and visual storytelling.',
    impact: ['Increased client engagement'],
    techStack: ['Next.js'],
    images: [
      '/doi creative/Bloom-Ty - Google Chrome 18-Dec-25 12_47_03 PM.png',
      '/doi creative/Bloom-Ty - Google Chrome 18-Dec-25 12_46_56 PM.png',
      '/doi creative/Bloom-Ty - Google Chrome 18-Dec-25 12_47_09 PM.png',
      '/doi creative/Bloom-Ty - Google Chrome 18-Dec-25 12_47_17 PM.png',
      '/doi creative/Bloom-Ty - Google Chrome 18-Dec-25 12_47_26 PM.png',
      '/doi creative/Bloom-Ty - Google Chrome 18-Dec-25 12_47_34 PM.png',
      '/doi creative/Bloom-Ty - Google Chrome 18-Dec-25 12_47_43 PM.png',
      '/doi creative/Bloom-Ty - Google Chrome 18-Dec-25 12_47_48 PM.png',
      '/doi creative/doi-creative.vercel.app_ (1).png',
      '/doi creative/doi-creative.vercel.app_ (2).png',
      '/doi creative/Screenshot_20251218_114503_Chrome.jpg',
      '/doi creative/Screenshot_20251218_114524_Chrome.jpg',
    ],
    isFeatured: false,
  },
];

export const getProjects = () => projectsData;
export const getFeaturedProjects = () => projectsData.filter(p => p.isFeatured).slice(0, 4);
export const getProjectBySlug = (slug) => projectsData.find(p => p.slug === slug);